name: incode_group_test_task
description: "Test project for IncodeGroup application"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.2
  retrofit: ^4.4.2
  logger: ^2.5.0 
  dio: ^5.7.0
  get_it: ^8.0.3
  injectable: ^2.5.0
  dart_mappable: ^4.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.14
  retrofit_generator: ^9.0.0
  injectable_generator: ^2.6.2
  dart_mappable_builder: ^4.3.0

flutter:
  uses-material-design: true
